import React from 'react'
import { Metadata } from 'next';
import Layout from '@/layout/layout';
import { Hero } from '@/components';

export const metadata: Metadata = {
  title: "JasurCoder - Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <Layout>
      <Hero />
    </Layout>
  )
}

export default Home
