import React from 'react'
import { Metadata } from 'next';
import { Button } from '@mui/material';
import Layout from '@/layout/layout';

export const metadata: Metadata = {
  title: "JasurCoder - Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <Layout>
      <Button>Click</Button>
    </Layout>
  )
}

export default Home
